### ISSUE TITLE
Can't install dependencies

### ISSUE THREAD

**Issue by GuyPie** [dydxprotocol/v4-web#59]
When trying to install dependencies I'm getting an error -  ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@dydxprotocol/v4-proto/-/v4-proto-0.2.1.tgz: Not Found - 404

**Comment by aforaleka** [comment]
hi @GuyPie, thanks for reporting this! please try again now and let us know if you run into any issues.

**Comment by GuyPie** [comment]
still not working on latest main version, getting the same error.

**Comment by webaifei** [comment]
> still not working on latest main version, getting the same error.

+1
