### ISSUE TITLE
Update Aave logo

### ISSUE THREAD

**Issue by omahs** [dydxprotocol/v4-web#777]
The Aave logo here https://github.com/dydxprotocol/v4-web/blob/main/public/currencies/aave.png could be updated. 

Here's the new logo in 128x128

![aave](https://github.com/dydxprotocol/v4-web/assets/73983677/d5b7f3bf-5fdd-4787-9cdb-9bfcb3590604)

More info here: https://github.com/aave-dao/aave-brand-kit

**Comment by moo-onthelawn** [comment]
https://github.com/dydxprotocol/v4-web/pull/780/
